### ISSUE TITLE
Play games plugin dependency.

### ISSUE THREAD

**Issue by Moghul** [aquto/kochava-phonegap#1]
Plugins that have this line:
`<framework src="com.google.android.gms:play-services-gcm:+" />`

In their plugin.xml are incompatible with this one because of your dependency to the google play services plugin. The phonegap-plugin-push is one of them and it is more crucial to the app than this one. 

Replacing `<dependency id="com.google.playservices" />` with the line above allowed me to build but I haven't tested actual functionality yet.

**Comment by jrunge** [comment]
Yeah, I've made that change in the cordova4 branch. You can use that branch until the change gets merged to master

**Comment by Moghul** [comment]
Thank you!
